### ISSUE TITLE
Indexer dies often on M1

### ISSUE THREAD

**Issue by dakom** [kurtosis-tech/near-package#18]
I mentioned this on Near's discord, but it's a pervasive problem so figured it's worth opening an issue here

the `kurtosistech/near-indexer-for-explorer` module dies on me often. Like, sometimes in the span of minutes within restarting.

I'm on M1 so not sure if that's the problem...

`docker logs` don't say much, just that it was killed :/

Happy to provide any more info, just let me know :)

**Comment by mieubrisse** [comment]
Going to close this since stale
