### ISSUE TITLE
launch-local-near-cluster.sh script launch problem

### ISSUE THREAD

**Issue by TarasMatolinets** [kurtosis-tech/near-package#41]
Hello everyone. I'm trying to configure local.test network and I'm getting error with after this ~/launch-local-near-cluster.sh. In attached you will see more details about this error. Maybe someone may help me with this
`~/launch-local-near-cluster.sh
Error: An error occurred running command 'run'
 --- at /home/circleci/project/cli/cli/command_framework/lowlevel/lowlevel_kurtosis_command.go:295 (LowlevelKurtosisCommand.MustGetCobraCommand.func2) ---
Caused by: An error occurred calling the run function for command 'run'
 --- at /home/circleci/project/cli/cli/command_framework/highlevel/engine_consuming_kurtosis_command/engine_consuming_kurtosis_command.go:149 (EngineConsumingKurtosisCommand.getRunFunc.func1) ---
Caused by: An error occurred getting the enclave context for enclave 'near'
 --- at /home/circleci/project/cli/cli/commands/run/run.go:210 (run) ---
Caused by: An error occurred while getting context for existing enclave with identifier 'near'
 --- at /home/circleci/project/cli/cli/commands/run/run.go:332 (getOrCreateEnclaveContext) ---
Caused by: An error occurred creating an enclave context from the returned enclave info
 --- at /home/circleci/project/api/golang/engine/lib/kurtosis_context/kurtosis_context.go:110 (KurtosisContext.GetEnclaveContext) ---
Caused by: Enclave containers status was 'EnclaveContainersStatus_STOPPED', but we can't create an enclave context from a non-running enclave
 --- at /home/circleci/project/api/golang/engine/lib/kurtosis_context/kurtosis_context.go:331 (newEnclaveContextFromEnclaveInfo) ---
Error: An error occurred executing package 'github.com/kurtosis-tech/near-package'`

**Comment by gbouv** [comment]
Hey @TarasMatolinets
Given the error above, can you try running `kurtosis enclave rm near` and retry the script?
I am on latest version of kurtosis and I just tried it, it runs just fine. Let me know if that fixes your issue.

**Comment by TarasMatolinets** [comment]
@gbouv Yes this it's works
