### ISSUE TITLE
Encountering issues while running launch-local-near-cluster.sh remotely.

### ISSUE THREAD

**Issue by WuDi329** [kurtosis-tech/near-package#47]
I am remotely connecting to the server via SSH, and I need to deploy a NEAR private chain on this server. As you can see, the server IP is 49.52.27.50.
![image](https://github.com/kurtosis-tech/near-package/assets/55496466/04921267-bc79-464c-929f-235d75f35d4b)
  However, it keeps throwing errors.“Error in cloning git repository 'https://github.com/kurtosis-tech/near-package.git' to '/kurtosis-data/tmp-startosis-packages/tmp-repo-dir-3945281040/kurtosis-tech/near-package'. Make sure that 'https://github.com/kurtosis-tech/near-package.git' exists and is a public repository.”

When I run the script directly without IP, it runs fine. But in this case, I encounter strange errors.
![image](https://github.com/kurtosis-tech/near-package/assets/55496466/5a5e79ef-6432-415f-8296-2c19c5c767e2)
For example, I am unable to add users at this time.
Looking forward to response, Thanks!

**Comment by laurentluce** [comment]
@WuDi329 What version of Kurtosis are you on?  CLI: `kurtosis version`.

**Comment by WuDi329** [comment]
> @WuDi329 What version of Kurtosis are you on? CLI: `kurtosis version`.

Thanks for your reply!

0.84.7

![image](https://github.com/kurtosis-tech/near-package/assets/55496466/623deb74-8f0c-4175-9a4c-3d7ab83c8f55)

Actually, I successfully launched the local Near cluster using the command: `~/launch-local-near-cluster.sh '{"backend_ip_addressd":"49.52.27.50"}'`. However, the webpage it generates still has some issues. For example, the URL displayed at the top of the page shows "127.0.0.1:8332", but I believe it should be displayed as "49.52.27.50:8332".

![image](https://github.com/kurtosis-tech/near-package/assets/55496466/13d3ce31-f854-4372-9750-ba348af81f4a)


The attempts I made were based on the instructions provided on this page: https://docs.near.org/develop/testing/kurtosis-localnet. However, I just discovered another guide for deploying a local Near chain at https://near-nodes.io/validator/running-a-node. I'm wondering about the relationship between these two guides and when to use each of them.

**Comment by h4ck3rk3y** [comment]
Hey! @WuDi329 Glad you could get it to work!

Is the URL on top a breaking change or a cosmetic one? We can track that in a separate ticket

I wasn't aware of the second page but I am guessing it is for people who don't have Kurtosis and want a pure docker setup.

**Comment by WuDi329** [comment]
> Hey! @WuDi329 Glad you could get it to work!
> 
> Is the URL on top a breaking change or a cosmetic one? We can track that in a separate ticket
> 
> I wasn't aware of the second page but I am guessing it is for people who don't have Kurtosis and want a pure docker setup.

Thanks for your reply! @h4ck3rk3y 

I don't quite understand your definitions of "breaking change" and "cosmetic change." Could you please explain them in detail?

It is disappointing that when I pass the IP address of the remote host as a parameter, the output remains the same as without this parameter. I am not entirely sure if I made an error in my operations. My complete steps are as follows:
1. ssh remote host(49.52.27.50)
2. execute `~/launch-local-near-cluster.sh '{"backend_ip_addressd":"49.52.27.50"}'` on the host
3. waiting for the result
4.  The output looks exactly like the image below:


![image](https://github.com/kurtosis-tech/near-package/assets/55496466/566c4267-1489-4744-b182-b408b65cb3b2)

**Comment by WuDi329** [comment]
Actually, the issue I encountered is this: `2023-10-24 11:05:46.402 ERROR poco_client::app::backend: Failed to set up the database, error: JsonRpc error: error while parsing the method call result: [missing field node_public_key]` 

The two attached images are the results returned by the Near node and the specific error message.

![image](https://github.com/kurtosis-tech/near-package/assets/55496466/fcecefe7-612e-4e48-9f91-fd6979ddb312)

![image](https://github.com/kurtosis-tech/near-package/assets/55496466/59db7392-5985-4f88-abf5-87c7e7fae9bf)

I found the update log for Near Core, which indicates that the node_key has been deprecated and node_public_key is now being used.

https://github.com/near/nearcore/blob/c3e9b5f13898f5530276649d9bec752d33d09da8/CHANGELOG.md?plain=1#L127

![47bf8154e4d5fa06e94fe4f1dca0161](https://github.com/kurtosis-tech/near-package/assets/55496466/a0e4c318-1faf-4ac7-a0f0-a78941ab0470)


So I wonder if this "missing field node_public_key" error is caused by an outdated version.

**Comment by h4ck3rk3y** [comment]
Hey @WuDi329 

> I don't quite understand your definitions of "breaking change" and "cosmetic change." Could you please explain them in detail?

The UI showing 127.0.0.1 - is that affecting workflows or is it just appearance? Weirdly enough when I open the URL from my browser I get the right ip address

<img width="1360" alt="image" src="https://github.com/kurtosis-tech/near-package/assets/6670312/a62c44e5-7c7e-465e-8521-87bfbb36192a">

The output of the `kurtosis enclave inspect` or whatever is printed after the enclave runs will always show locally mapped ports as that is running on the remote machine.

But we could tweak the bash script to print the wallet public ip address;

Can you tell me where you are seeing those logs?

The changelog you mentioned is from 9 months ago; we have pinned images which are more than 10 months old as we haven't been actively working on this package. Our tests while fixing the package involve sending NEAR from one test wallet to another using the UI launched via Kurtosis.

I wonder whether you are using local_near/near-cli or something and that CLI is a lot older than what works with the near-package? I would recommend trying an older CLI in that case - 1.30 or prior

**Comment by WuDi329** [comment]
Thanks for your reply! @h4ck3rk3y 

> The UI showing 127.0.0.1 - is that affecting workflows or is it just appearance? Weirdly enough when I open the URL from my browser I get the right ip address

Before, I believed it would affect the functionality, specifically, I attributed `[missing field node_public_key]` to this issue. But now, I am not so sure anymore.

> But we could tweak the bash script to print the wallet public ip address;

However, I still haven't been able to change the public IP address by tweaking the bash script.

I have written these scripts into .bashrc, but after running them, the public IP address did not change. I would like to know how you changed it？

![image](https://github.com/kurtosis-tech/near-package/assets/55496466/e38da910-ed24-4c4b-ab31-7743ea7c8f13)

After running, the URL of the page still remains as 127.0.0.1.


> Can you tell me where you are seeing those logs?

Are you referring to this image?

![image](https://github.com/kurtosis-tech/near-package/assets/55496466/6ff82b34-7659-42ae-be93-f5d20a1dc365)

This is the log recorded by the program I ran, specifically, it should be the result returned by Near.

> I wonder whether you are using local_near/near-cli or something and that CLI is a lot older than what works with the near-package? I would recommend trying an older CLI in that case - 1.30 or prior

I'm not quite sure I understand this sentence.  Do you mean I need to download an older version of near-cli? The version of near-cli I was using before is 3.4.2. I couldn't find version 1.30 of near-cli. Then I downgraded it to 3.0.0, but I still get the error [missing field node_public_key].

![image](https://github.com/kurtosis-tech/near-package/assets/55496466/0c721f95-fa4c-40b9-be45-dc0495d794c1)

> The changelog you mentioned is from 9 months ago; we have pinned images which are more than 10 months old as we haven't been actively working on this package. Our tests while fixing the package involve sending NEAR from one test wallet to another using the UI launched via Kurtosis.

My second question is, do I have any way to revert Near-related libraries (or something else, I'm not sure how to express it clearly) to older versions so that the discarded node_key node_key can make the program run?

The program I am running can be found on my homepage at https://github.com/WuDi329/PoCo. First, I need to deploy the contract in the poco-contract directory, and then I need to run 'cargo build' and 'cargo run daemon' in the poco-agent directory. I want to know if I need to downgrade some dependencies of this library in order to make the program run.

**Comment by WuDi329** [comment]
I have also posted a stream in the Near community to discuss the issues I encountered and requested their solutions(https://near.zulipchat.com/#narrow/stream/295302-general/topic/localnet.20set.20wallet.20.26.20explorer). They suggested that I consider building the relevant modules locally, including Near Explorer and Near Wallet, but I couldn't find any related documentation. Do you have any suggestions or opinions on this? @h4ck3rk3y

**Comment by WuDi329** [comment]
I have no more questions to ask about this issue. Thank you very much for your reply. @h4ck3rk3y But I encountered some problems when building the image. I have opened a new issue here(https://github.com/kurtosis-tech/near-package/issues/48). I hope to get your help. Thank you again!
